apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name:  pod
  namespace: default
subjects:
- kind: ServiceAccount  
  name: jane
  namespace: default
roleRef:
  kind: ClusterRole 
  name: test
  apiGroup: rbac.authorization.k8s.io