apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: test-network-policy
  namespace: default  # we make sure a network policy exists on this namespace
---
# CiliumNetworkPolicy example
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: test-cilium-network-policy
  namespace: default  # CiliumNetworkPolicy also counts as a network policy in this namespace