apiVersion: v1
kind: Pod
metadata:
    name: test
spec:
      containers:
      - image: nginx:latest
        name: test
      - name : test2
        image : nginx
        securityContext:
          privileged: true