apiVersion: v1
kind: Pod
metadata:
  name: audit-pod
  labels:
    app: audit-pod
spec:
  containers:
  - name: test-container
    env :
      - name : azure_batch_key
        value : "Hello from the environment"
    image: hashicorp/http-echo:0.2.3
    securityContext:
      capabilities:
        add: ["NET_ADMIN", "SYS_ADMIN"]
      allowPrivilegeEscalation: true
  - name : test-container2
    env :
        - name : random
          value : "Hello from the environment"
    image : hashicorp/http-echo:0.2.3
