apiVersion: v1
kind: Pod
metadata:
  name: envar-demo
  labels:
    purpose: demonstrate-envars
spec:
  containers:
  - name: envar-demo-container
    image: gcr.io/google-samples/node-hello:latest
    securityContext:
      runAsUser: 0
  - name: envar-demo-container2
    image: gcr.io/google-samples/node-hello:11.2
    securityContext:
      runAsUser: 0
