apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec :
          hostNetwork: true
          containers :
            -
              name : mysql
              image : mysql
              env :
                -
                  name : MYSQL_ROOT_PASSWORD
                  value : "rootpasswd"
              volumeMounts :
                -
                  mountPath : /var/lib/mysql
                  name : site-data
                  subPath : mysql
              securityContext:
                readOnlyRootFilesystem: false
                seLinuxOptions:
                  level: "s0:c123,c456"
            -
              name : php
              image : php:7.0-apache
              volumeMounts :
                -
                  mountPath : /var/www/html
                  name : site-data
                  subPath : html
          volumes :
            -
              name : site-data
              persistentVolumeClaim :
                claimName : my-lamp-site-data
          restartPolicy: OnFailure
          