name: Kubescape scanning for misconfigurations

on: [push]

jobs:
 test_ks_misconfigurations:  
    uses: kubescape/workflows/.github/workflows/ks-ga-flow.yaml@547a98f361e0713832308e3f34165bb89fd9b08c # main
    with:
      FRAMEWORKS: "nsa,mitre,cis-eks-t1.7.0,cis-eks-t1.8.0,cis-aks-t1.8.0,cis-v1.10.0,cis-v1.12.0"
    secrets: inherit
