# The action is used to sync documentation of controls library with `kubescape.io` website
# The action checks for any files that are out of sync
# And opens a pull request in the target repository with the changes(if any)

name: Sync Files

on:
  push:
    branches:
      - master
    paths:
      - 'docs/controls/**' # The action is triggered everytime there is a push to the defined path 
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
      - name: Run GitHub File Sync
        uses: BetaHuhn/repo-file-sync-action@v1
        with:
          GH_PAT: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          COMMIT_BODY: "Sync documentation of controls library from `regolibrary` repository"
          PR_BODY: Syncing the Control Library docs from `regolibrary` repository to update the `controls` documentation
          PR_LABELS: automerge
          COMMIT_PREFIX: ""
